Transform: AWS::Serverless-2016-10-31
Description: EventBridge POC

Resources:
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: fargate-poc-eventbus

# route FargatePoc events to Fargate task
  FargatePocEventListener:
    Type: AWS::Events::Rule
    Properties:
      Description: "Handle FargatePoc events"
      EventBusName: !GetAtt EventBus.Name
      # EventPattern: {"source": ["fargate-poc"], "detail": {"bucket": {"name": ["somebucket"]}}, "detail-type": ["Object Created"]}
      EventPattern: {"source": ["fargate-poc"]}
      Targets:
        - Id: fargate-poc
          RoleArn: !GetAtt FargatePocEventRole.Arn
          Arn: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/default
          EcsParameters:
            LaunchType: FARGATE
            PlatformVersion: LATEST
            TaskDefinitionArn: !Ref FargatePocTaskDefinition
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: ENABLED
                Subnets:
                  - subnet-4efb1d2a
                  - subnet-82b0bff5
                  - subnet-97f1d6ce
          InputTransformer:
            InputPathsMap:
              bucket_name: "$.detail.bucket.name"
              object_key: "$.detail.object.key"
              objectversionid: "$.detail.object.version-id"
              source: $.source
              detail: $.detail
              detailType: $.detail-type
            InputTemplate: |
              {
                "containerOverrides": [
                  {
                    "name": "eventbridge-fargate-poc",
                    "environment": [
                      {
                        "name": "BUCKET_NAME",
                        "value": <bucket_name>
                      },
                      {
                        "name": "S3_OBJECT_KEY",
                        "value": <object_key>
                      },
                      {
                        "name": "EVENT_DETAIL",
                        "value": <detail>
                      },
                      {
                        "name": "EVENT_DETAIL_TYPE",
                        "value": <detailType>
                      }
                    ]
                  }
                ]
              }

  FargatePocEventRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: eventbridge-runtask
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecs:RunTask
                Resource: !Ref FargatePocTaskDefinition
                Condition:
                  ArnLike:
                    "ecs:cluster": arn:aws:ecs:*:403154239519:cluster/default
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: "*"

  FargatePocTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - "FARGATE"
      NetworkMode: awsvpc
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole
      TaskRoleArn: !GetAtt FargatePocTaskRole.Arn
      Cpu: "256"
      Memory: "512"
      RuntimePlatform:
        CpuArchitecture: "ARM64"
      Family: eventbridge-fargate-poc
      ContainerDefinitions:
        - Name: eventbridge-fargate-poc
          Image: !Sub 403154239519.dkr.ecr.eu-west-1.amazonaws.com/eventbridge-fargate-poc:latest
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /aws/lambda/eventbridge-fargate-poc
              awslogs-region: eu-west-1
              awslogs-stream-prefix: backend

  FargatePocTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: eventbridge-fargate-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:Put*
                Resource: "*"
      Path: "/"

  FargatePocLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/eventbridge-fargate-poc
      RetentionInDays: 90

# eof
